### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by chimmmpie** [soltecsis/fwcloud-docker#5]
I have cloned the repository and executed `docker-compose up -d`. This boots up 3 containers. 

No errors are observed in the logs of the container (docker logs <container name>. After a few minutes still no response on port 3030. Port is bound by the container. But if i run curl server:3030 i get `Empty reply from server`

**Comment by cmunyoz** [comment]
I think that it would be better comment problems like this in the FWCloud forum (forum.fwcloud.net).
May you post it in the `Installation and configuration` section?
